name: khavan
services:
  stock-assistant:
    container_name: khavan-stock-assistant
    build: 
      context: ..
      dockerfile: config/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ..:/app
    networks:
      - stock-assistant
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://stock-assistant:8501/_stcore/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  nginx:
    container_name: khavan-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - stock-assistant
    depends_on:
      - stock-assistant
    restart: always

networks:
  stock-assistant:
    driver: bridge